### ISSUE TITLE
Incomplete function

### ISSUE THREAD

**Issue by urmichm** [rafalk342/bfs-cuda#2]
Hello, in the bfsCUDA.cu file, the last character  } does not have a pair. 
Could you review the function 
__global__ void assignVerticesNextQueue(...) ? It seems that this function is not complete :)
Thanks a lot

**Comment by rafalk342** [comment]
The last character } matches with 
https://github.com/rafalk342/bfs-cuda/blob/bfb99a555ebd6d5f0edcc1d62b86bc8547cf4488/bfsCUDA.cu#L5

I tried to compile the code and it builds.

**Comment by urmichm** [comment]
Yes, man! You are right, I totally forgot about this line yesterday. Thank you! 

Could you still check this assignVerticesNextQueue(...) Kernel function, how do you update nextQueueSize  variable in the kernel?

**Comment by rafalk342** [comment]
I see now that nextQueueSize is not used in assignVerticesNextQueue(...) kernel function. 
I update the size of the next queue here:
https://github.com/rafalk342/bfs-cuda/blob/bfb99a555ebd6d5f0edcc1d62b86bc8547cf4488/main.cpp#L256

**Comment by urmichm** [comment]
Thanks a lot
